sudo: required

services:
  - docker

script:
  - docker build -t lets-test-me .
  - docker run lets-test-me /bin/sh -c 'source "$HOME/.sdkman/bin/sdkman-init.sh" && (cordova create test && cd test && cordova platform add android && cordova build android)'
